/**
 * Report-shape compatibility between the pinned scan engine and the pinned
 * schema (issue #5).
 *
 * The server spawns `@vibecodeqa/cli` at `CLI_SPEC` and feeds its JSON straight
 * into `parseReport` from `@vibecodeqa/schema`. Those are two independently
 * versioned pins, and nothing previously checked that they agree — the pin sat
 * on `^0.45.0` for nine CLI minors while the cached-report path at
 * `runScan()` was already ingesting whatever the user's own CLI had written.
 *
 * This runs offline against a committed fixture — a real report emitted by the
 * pinned engine, with issue lists and tool output trimmed and absolute paths
 * scrubbed. Running the actual engine here would put an `npx --yes` network
 * install on the publish gate, which #4 explicitly keeps off it.
 *
 * The fixture is therefore load-bearing: when `CLI_SPEC` moves, regenerate it
 * from the newly pinned engine. The first test below fails until you do, which
 * is the mechanism that stops the pin drifting silently again.
 */

import { ok, strictEqual } from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { describe, it } from "node:test";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { CHECK_META, parseReport } from "@vibecodeqa/schema";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const fixtureDir = join(here, "fixture");

/** The engine version pinned in src/index.ts, read from the source. */
function pinnedCliRange() {
	const src = readFileSync(join(repoRoot, "src", "index.ts"), "utf8");
	const m = src.match(/const CLI_SPEC = "@vibecodeqa\/cli@([^"]+)"/);
	ok(m, "could not find CLI_SPEC in src/index.ts");
	return m[1];
}

/** The committed report fixture, and the CLI version it was generated by. */
function fixtureReport() {
	const names = readdirSync(fixtureDir).filter((f) => /^report-cli-.*\.json$/.test(f));
	strictEqual(
		names.length,
		1,
		`expected exactly one report-cli-*.json fixture, found ${names.length}: ${names.join(", ")} — ` +
			"delete the stale one when you regenerate it for a new pin",
	);
	const raw = JSON.parse(readFileSync(join(fixtureDir, names[0]), "utf8"));
	return { name: names[0], raw };
}

/**
 * Checks a current CLI emits that the pinned schema has no CHECK_META entry for.
 *
 * Empty: `dead-code`, the one gap recorded here under schema 0.4.2, has had
 * CHECK_META since schema 0.5.0, and the 0.57 engine's new
 * `cloudflare-worker-mcp` check is documented too.
 *
 * Anything NOT on this list is a new gap and fails. Never grow it without a
 * reason written here.
 */
const KNOWN_UNEXPLAINABLE_CHECKS = new Set([]);

describe("pinned CLI ↔ pinned schema compatibility", () => {
	const { name, raw } = fixtureReport();

	it("has a fixture generated by the currently pinned engine", () => {
		const range = pinnedCliRange();
		// `^0.57.0` is a 0.x caret: a MINOR range, resolving within 0.57.x only.
		const pinnedMinor = range.replace(/^[^0-9]*/, "").split(".").slice(0, 2).join(".");
		const fixtureVersion = String(raw.version ?? "");
		const fixtureMinor = fixtureVersion.split(".").slice(0, 2).join(".");
		strictEqual(
			fixtureMinor,
			pinnedMinor,
			`fixture ${name} was generated by CLI ${fixtureVersion}, but CLI_SPEC pins ${range}. ` +
				"Regenerate it: `npx @vibecodeqa/cli@<pinned> --skip-tests --json .` on a real project, " +
				"trim the issue lists, scrub absolute paths, and rename the file to match.",
		);
	});

	it("parses a pinned-engine report with the pinned schema", () => {
		// This is the assertion that would have caught a genuine breaking change
		// in the report shape across the nine minors the pin skipped.
		const report = parseReport(raw);
		strictEqual(report.checks.length, raw.checks.length, "parseReport dropped checks");
		ok(report.checks.length > 30, `only ${report.checks.length} checks survived the parse`);
	});

	it("keeps the metadata the server's tools actually read", () => {
		const report = parseReport(raw);
		ok(report.meta.filesScanned > 0, "meta.filesScanned lost in the parse");
		ok(report.meta.stack, "meta.stack lost in the parse");
		for (const c of report.checks) {
			ok(typeof c.name === "string" && c.name.length > 0, "check with no name");
			ok(Array.isArray(c.issues), `check ${c.name} has no issues array`);
		}
	});

	it("carries the tool provenance the pinned engine added in 0.52.0", () => {
		// details.toolRuns[] is the trust data vcqa_scan/vcqa_check hand an agent —
		// exact command, working directory, ok/failed. The old 0.45 pin never emitted it.
		const report = parseReport(raw);
		const withRuns = report.checks.filter((c) => Array.isArray(c.details?.toolRuns) && c.details.toolRuns.length > 0);
		ok(withRuns.length > 0, "no check carries details.toolRuns — is the fixture from a pre-0.52 engine?");
		for (const c of withRuns) {
			for (const run of c.details.toolRuns) {
				ok(run.tool, `${c.name} has a toolRun with no tool name`);
				ok(run.command, `${c.name} has a toolRun with no command`);
			}
		}
	});

	it("carries fingerprint v2 identities through the parse", () => {
		// The 0.57 engine re-keys findings (meta.fingerprintVersion: 2). The
		// server passes reports through to agents, so the marker and the
		// per-issue fingerprints must survive parseReport untouched.
		const report = parseReport(raw);
		strictEqual(report.meta.fingerprintVersion, 2, "meta.fingerprintVersion lost or not 2 — is the fixture from a pre-0.57 engine?");
		const issues = report.checks.flatMap((c) => c.issues);
		ok(issues.length > 0, "fixture has no issues to carry fingerprints");
		for (const i of issues) ok(typeof i.fingerprint === "string" && i.fingerprint.length > 0, `issue without a fingerprint: ${i.message}`);
	});

	it("keeps the report-level provenance the 0.57 engine writes", () => {
		// meta.git / meta.scan, typed from schema 0.6.0. vcqa_scan hands the
		// report to agents verbatim, so a parse that dropped them would hide
		// which commit a result describes.
		const report = parseReport(raw);
		ok(report.meta.git && typeof report.meta.git.sha === "string", "meta.git.sha lost in the parse");
		ok(report.meta.scan && typeof report.meta.scan.id === "string", "meta.scan.id lost in the parse");
	});

	it("keeps per-run provenance on every tool run", () => {
		const report = parseReport(raw);
		const runs = report.checks.flatMap((c) => (Array.isArray(c.details?.toolRuns) ? c.details.toolRuns : []).map((r) => [c.name, r]));
		ok(runs.length > 0, "no tool runs in the fixture");
		for (const [name, run] of runs) {
			strictEqual(typeof run.cwd, "string", `${name}/${run.tool} has no cwd`);
			strictEqual(typeof run.ok, "boolean", `${name}/${run.tool} has no ok flag`);
			strictEqual(typeof run.durationMs, "number", `${name}/${run.tool} has no durationMs`);
			strictEqual(typeof run.status, "string", `${name}/${run.tool} has no status`);
		}
	});

	it("can explain every check the pinned engine emits", () => {
		const report = parseReport(raw);
		const missing = report.checks
			.map((c) => c.name)
			.filter((n) => !CHECK_META[n] && !KNOWN_UNEXPLAINABLE_CHECKS.has(n));
		strictEqual(
			missing.length,
			0,
			`the pinned schema has no CHECK_META for: ${missing.join(", ")} — ` +
				"vcqa_explain and vcqa_check would have no label, category, weight or fix advice for these. " +
				"Bump @vibecodeqa/schema, or record the gap in KNOWN_UNEXPLAINABLE_CHECKS with a reason.",
		);
	});

	it("still covers the checks the schema bump was made for", () => {
		// flutter / cloudflare-workers / sqlite-d1 had no CHECK_META entry under
		// schema 0.2.0; they are the reason the schema pin moved with the CLI pin.
		for (const n of ["flutter", "cloudflare-workers", "sqlite-d1"]) {
			ok(CHECK_META[n], `CHECK_META lost its ${n} entry — the schema pin regressed`);
		}
	});

	it("does not leak the machine the fixture was generated on", () => {
		const text = readFileSync(join(fixtureDir, name), "utf8");
		ok(!/\/Users\/[a-z]/i.test(text), "fixture contains a real home directory path — scrub it");
	});
});
